[2025-05-02T18:24:47.911+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.split_dataset scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T18:24:47.917+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.split_dataset scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T18:24:47.918+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T18:24:47.928+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): split_dataset> on 2025-05-01 00:00:00+00:00
[2025-05-02T18:24:47.932+0000] {standard_task_runner.py:60} INFO - Started process 1867 to run task
[2025-05-02T18:24:47.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'split_dataset', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpwmfu3z_o']
[2025-05-02T18:24:47.936+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask split_dataset
[2025-05-02T18:24:47.973+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.split_dataset scheduled__2025-05-01T00:00:00+00:00 [running]> on host 82b06739c44f
[2025-05-02T18:24:48.033+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='split_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T18:24:48.042+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvi0ks21l6 --system-site-packages --python=python
[2025-05-02T18:24:48.050+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:48.671+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 350ms
[2025-05-02T18:24:48.671+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvi0ks21l6, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T18:24:48.672+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpf8y0e9ou)
[2025-05-02T18:24:48.673+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T18:24:48.674+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T18:24:48.701+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvi0ks21l6/bin/pip install -r /tmp/venvi0ks21l6/requirements.txt
[2025-05-02T18:24:48.712+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:49.603+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T18:24:49.853+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvi0ks21l6/requirements.txt (line 1))
[2025-05-02T18:24:49.901+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T18:24:49.905+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.17.2)
[2025-05-02T18:24:49.906+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvi0ks21l6/requirements.txt (line 3)) (1.3.2)
[2025-05-02T18:24:49.947+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (1.37.38)
[2025-05-02T18:24:49.949+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (1.37.38)
[2025-05-02T18:24:49.950+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (1.24.4)
[2025-05-02T18:24:49.950+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (23.2)
[2025-05-02T18:24:49.952+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (2.0.3)
[2025-05-02T18:24:49.954+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (14.0.2)
[2025-05-02T18:24:49.955+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (4.9.0)
[2025-05-02T18:24:50.001+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.17.2)
[2025-05-02T18:24:50.006+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.2.5)
[2025-05-02T18:24:50.008+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.13.1)
[2025-05-02T18:24:50.015+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (7.0.0)
[2025-05-02T18:24:50.020+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.4.3)
[2025-05-02T18:24:50.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.5.2)
[2025-05-02T18:24:50.029+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.7.5)
[2025-05-02T18:24:50.033+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.10.1)
[2025-05-02T18:24:50.037+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.4.51)
[2025-05-02T18:24:50.044+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.1.3)
[2025-05-02T18:24:50.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (21.2.0)
[2025-05-02T18:24:50.054+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (5.3.2)
[2025-05-02T18:24:50.063+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (8.1.7)
[2025-05-02T18:24:50.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.1.1)
[2025-05-02T18:24:50.083+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (0.51.0)
[2025-05-02T18:24:50.089+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.1.44)
[2025-05-02T18:24:50.094+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (6.11.0)
[2025-05-02T18:24:50.098+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.22.0)
[2025-05-02T18:24:50.100+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.22.0)
[2025-05-02T18:24:50.102+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (4.25.2)
[2025-05-02T18:24:50.105+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (6.0.1)
[2025-05-02T18:24:50.113+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.31.0)
[2025-05-02T18:24:50.115+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (0.4.4)
[2025-05-02T18:24:50.119+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvi0ks21l6/requirements.txt (line 3)) (1.4.2)
[2025-05-02T18:24:50.124+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvi0ks21l6/requirements.txt (line 3)) (3.5.0)
[2025-05-02T18:24:50.129+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.3.0)
[2025-05-02T18:24:50.133+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (5.13.0)
[2025-05-02T18:24:50.137+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (0.10.0)
[2025-05-02T18:24:50.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (0.11.5)
[2025-05-02T18:24:50.148+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (2.8.2)
[2025-05-02T18:24:50.156+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (1.26.18)
[2025-05-02T18:24:50.162+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.2.3)
[2025-05-02T18:24:50.165+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.1.2)
[2025-05-02T18:24:50.171+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.2.6)
[2025-05-02T18:24:50.187+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.2.0)
[2025-05-02T18:24:50.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.1.3)
[2025-05-02T18:24:50.202+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.1.1)
[2025-05-02T18:24:50.203+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (0.12.1)
[2025-05-02T18:24:50.204+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (4.57.0)
[2025-05-02T18:24:50.204+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.4.7)
[2025-05-02T18:24:50.205+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (10.4.0)
[2025-05-02T18:24:50.205+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.1.1)
[2025-05-02T18:24:50.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (2023.3.post1)
[2025-05-02T18:24:50.294+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (2023.4)
[2025-05-02T18:24:50.381+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.0.3)
[2025-05-02T18:24:50.447+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2.26.2)
[2025-05-02T18:24:50.499+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (4.0.12)
[2025-05-02T18:24:50.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.17.0)
[2025-05-02T18:24:50.573+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.2.14)
[2025-05-02T18:24:50.580+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (0.43b0)
[2025-05-02T18:24:50.621+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvi0ks21l6/requirements.txt (line 1)) (1.16.0)
[2025-05-02T18:24:50.644+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.3.2)
[2025-05-02T18:24:50.645+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (3.6)
[2025-05-02T18:24:50.645+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (2023.11.17)
[2025-05-02T18:24:50.725+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (1.16.0)
[2025-05-02T18:24:50.733+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (5.0.2)
[2025-05-02T18:24:50.749+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (0.3.0)
[2025-05-02T18:24:50.750+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (4.9)
[2025-05-02T18:24:50.800+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvi0ks21l6/requirements.txt (line 2)) (0.5.1)
[2025-05-02T18:24:50.855+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T18:24:50.911+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 15.9 MB/s eta 0:00:00
[2025-05-02T18:24:52.810+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T18:24:53.048+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T18:24:53.178+0000] {process_utils.py:190} INFO - 
[2025-05-02T18:24:53.179+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T18:24:53.179+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T18:24:53.336+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvi0ks21l6/bin/python /tmp/venv-callxp4za_ms/script.py /tmp/venv-callxp4za_ms/script.in /tmp/venv-callxp4za_ms/script.out /tmp/venv-callxp4za_ms/string_args.txt /tmp/venv-callxp4za_ms/termination.log
[2025-05-02T18:24:53.344+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T18:24:53.907+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T18:24:55.636+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:55.635+0000[0m] {[34mscript.py:[0m48} INFO[0m - Starting to read processed dataset from s3://data/processed/stroke_data.csv[0m
[2025-05-02T18:24:55.646+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:55.645+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:24:55.701+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:55.701+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:24:55.745+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:55.745+0000[0m] {[34mscript.py:[0m53} INFO[0m - Processed dataset loaded successfully from s3://data/processed/stroke_data.csv[0m
[2025-05-02T18:24:55.748+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:55.748+0000[0m] {[34mscript.py:[0m61} INFO[0m - Target column for the dataset: log_cnt[0m
[2025-05-02T18:24:55.749+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:55.748+0000[0m] {[34mscript.py:[0m65} ERROR[0m - Target column 'log_cnt' not found in DataFrame. Available columns: ['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'][0m
[2025-05-02T18:24:55.751+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:55.751+0000[0m] {[34mvariable.py:[0m245} WARNING[0m - The variable target_col is defined in the LocalFilesystemBackend secrets backend, which takes precedence over reading from the database. The value in the database will be updated, but to read it you have to delete the conflicting variable from LocalFilesystemBackend[0m
[2025-05-02T18:24:56.095+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.094+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-05-02T18:24:56.099+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.098+0000[0m] {[34mscript.py:[0m69} INFO[0m - Setting target column to default value: stroke[0m
[2025-05-02T18:24:56.100+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.100+0000[0m] {[34mscript.py:[0m81} INFO[0m - Features and target separated successfully[0m
[2025-05-02T18:24:56.101+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.100+0000[0m] {[34mscript.py:[0m82} INFO[0m - Features shape: (5110, 16), Target shape: (5110,)[0m
[2025-05-02T18:24:56.101+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.101+0000[0m] {[34mscript.py:[0m86} INFO[0m - Class distribution in target column:
[2025-05-02T18:24:56.102+0000] {process_utils.py:190} INFO - stroke
[2025-05-02T18:24:56.102+0000] {process_utils.py:190} INFO - 0    95.127202
[2025-05-02T18:24:56.103+0000] {process_utils.py:190} INFO - 1     4.872798
[2025-05-02T18:24:56.103+0000] {process_utils.py:190} INFO - Name: proportion, dtype: float64[0m
[2025-05-02T18:24:56.112+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.112+0000[0m] {[34mscript.py:[0m103} INFO[0m - Test size for dataset split: 0.3[0m
[2025-05-02T18:24:56.117+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.117+0000[0m] {[34mscript.py:[0m110} INFO[0m - Dataset split into training and testing sets successfully[0m
[2025-05-02T18:24:56.118+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.117+0000[0m] {[34mscript.py:[0m111} INFO[0m - Training set size: (3577, 16), Testing set size: (1533, 16)[0m
[2025-05-02T18:24:56.119+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.119+0000[0m] {[34mscript.py:[0m116} INFO[0m - Class distribution in training set:
[2025-05-02T18:24:56.120+0000] {process_utils.py:190} INFO - stroke
[2025-05-02T18:24:56.121+0000] {process_utils.py:190} INFO - 0    95.135588
[2025-05-02T18:24:56.123+0000] {process_utils.py:190} INFO - 1     4.864412
[2025-05-02T18:24:56.124+0000] {process_utils.py:190} INFO - Name: proportion, dtype: float64[0m
[2025-05-02T18:24:56.124+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.119+0000[0m] {[34mscript.py:[0m117} INFO[0m - Class distribution in testing set:
[2025-05-02T18:24:56.125+0000] {process_utils.py:190} INFO - stroke
[2025-05-02T18:24:56.125+0000] {process_utils.py:190} INFO - 0    95.107632
[2025-05-02T18:24:56.126+0000] {process_utils.py:190} INFO - 1     4.892368
[2025-05-02T18:24:56.126+0000] {process_utils.py:190} INFO - Name: proportion, dtype: float64[0m
[2025-05-02T18:24:56.126+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.119+0000[0m] {[34mscript.py:[0m122} INFO[0m - Starting to save training and testing datasets to S3/Minio[0m
[2025-05-02T18:24:56.127+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.127+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:24:56.189+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.188+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:24:56.218+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.218+0000[0m] {[34mscript.py:[0m127} INFO[0m - Training features saved successfully to s3://data/train/stroke_data_X_train.csv[0m
[2025-05-02T18:24:56.225+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.225+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:24:56.352+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.351+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:24:56.374+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.374+0000[0m] {[34mscript.py:[0m130} INFO[0m - Testing features saved successfully to s3://data/test/stroke_data_X_test.csv[0m
[2025-05-02T18:24:56.381+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.381+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:24:56.434+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.433+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:24:56.457+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.456+0000[0m] {[34mscript.py:[0m133} INFO[0m - Training target saved successfully to s3://data/train/stroke_data_y_train.csv[0m
[2025-05-02T18:24:56.471+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.470+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T18:24:56.645+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.645+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T18:24:56.660+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.660+0000[0m] {[34mscript.py:[0m136} INFO[0m - Testing target saved successfully to s3://data/test/stroke_data_y_test.csv[0m
[2025-05-02T18:24:56.661+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.660+0000[0m] {[34mscript.py:[0m142} INFO[0m - Logging data split information to MLflow[0m
[2025-05-02T18:24:56.867+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.867+0000[0m] {[34mscript.py:[0m178} INFO[0m - Data split information logged to MLflow successfully in run: split_dataset_20250502_182456[0m
[2025-05-02T18:24:56.895+0000] {process_utils.py:190} INFO - 2025/05/02 18:24:56 INFO mlflow.tracking._tracking_service.client: 🏃 View run split_dataset_20250502_182456 at: http://mlflow:5000/#/experiments/1/runs/38ca28c7d4814a08a05516fd61fe42be.
[2025-05-02T18:24:56.896+0000] {process_utils.py:190} INFO - 2025/05/02 18:24:56 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-02T18:24:56.919+0000] {process_utils.py:190} INFO - [[34m2025-05-02T18:24:56.919+0000[0m] {[34mscript.py:[0m180} INFO[0m - Dataset splitting and saving completed successfully[0m
[2025-05-02T18:24:57.375+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T18:24:57.386+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=split_dataset, execution_date=20250501T000000, start_date=20250502T182447, end_date=20250502T182457
[2025-05-02T18:24:57.427+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T18:24:57.449+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-02T22:43:16.404+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.split_dataset scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:43:16.420+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.split_dataset scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:43:16.421+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T22:43:16.436+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): split_dataset> on 2025-05-01 00:00:00+00:00
[2025-05-02T22:43:16.442+0000] {standard_task_runner.py:60} INFO - Started process 567 to run task
[2025-05-02T22:43:16.447+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'split_dataset', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmptbn6omc0']
[2025-05-02T22:43:16.450+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask split_dataset
[2025-05-02T22:43:16.503+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.split_dataset scheduled__2025-05-01T00:00:00+00:00 [running]> on host 06c6f1d995e0
[2025-05-02T22:43:16.590+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='split_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T22:43:16.595+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvah8ozwhx --system-site-packages --python=python
[2025-05-02T22:43:16.603+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:43:17.437+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 436ms
[2025-05-02T22:43:17.437+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvah8ozwhx, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T22:43:17.438+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpb_mxzlsw)
[2025-05-02T22:43:17.439+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T22:43:17.440+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T22:43:17.481+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvah8ozwhx/bin/pip install -r /tmp/venvah8ozwhx/requirements.txt
[2025-05-02T22:43:17.490+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:43:18.322+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T22:43:18.650+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvah8ozwhx/requirements.txt (line 1))
[2025-05-02T22:43:18.695+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T22:43:18.698+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.17.2)
[2025-05-02T22:43:18.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvah8ozwhx/requirements.txt (line 3)) (1.3.2)
[2025-05-02T22:43:18.742+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (1.37.38)
[2025-05-02T22:43:18.743+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (1.37.38)
[2025-05-02T22:43:18.744+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (1.24.4)
[2025-05-02T22:43:18.745+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (23.2)
[2025-05-02T22:43:18.746+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (2.0.3)
[2025-05-02T22:43:18.747+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (14.0.2)
[2025-05-02T22:43:18.748+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (4.9.0)
[2025-05-02T22:43:18.801+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.17.2)
[2025-05-02T22:43:18.803+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.2.5)
[2025-05-02T22:43:18.804+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.13.1)
[2025-05-02T22:43:18.805+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (7.0.0)
[2025-05-02T22:43:18.806+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.4.3)
[2025-05-02T22:43:18.807+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.5.2)
[2025-05-02T22:43:18.808+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.7.5)
[2025-05-02T22:43:18.809+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.10.1)
[2025-05-02T22:43:18.810+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.4.51)
[2025-05-02T22:43:18.812+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.1.3)
[2025-05-02T22:43:18.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (21.2.0)
[2025-05-02T22:43:18.861+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (5.3.2)
[2025-05-02T22:43:18.862+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (8.1.7)
[2025-05-02T22:43:18.863+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.1.1)
[2025-05-02T22:43:18.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (0.51.0)
[2025-05-02T22:43:18.865+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.1.44)
[2025-05-02T22:43:18.865+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (6.11.0)
[2025-05-02T22:43:18.866+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.22.0)
[2025-05-02T22:43:18.866+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.22.0)
[2025-05-02T22:43:18.867+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (4.25.2)
[2025-05-02T22:43:18.867+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (6.0.1)
[2025-05-02T22:43:18.868+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.31.0)
[2025-05-02T22:43:18.868+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (0.4.4)
[2025-05-02T22:43:18.911+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvah8ozwhx/requirements.txt (line 3)) (1.4.2)
[2025-05-02T22:43:18.913+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn->-r /tmp/venvah8ozwhx/requirements.txt (line 3)) (3.5.0)
[2025-05-02T22:43:18.923+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.3.0)
[2025-05-02T22:43:18.924+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (5.13.0)
[2025-05-02T22:43:18.930+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (0.10.0)
[2025-05-02T22:43:18.931+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (0.11.5)
[2025-05-02T22:43:18.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (2.8.2)
[2025-05-02T22:43:18.938+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (1.26.18)
[2025-05-02T22:43:18.952+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.2.3)
[2025-05-02T22:43:18.953+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.1.2)
[2025-05-02T22:43:19.001+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.2.6)
[2025-05-02T22:43:19.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.2.0)
[2025-05-02T22:43:19.015+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.1.3)
[2025-05-02T22:43:19.042+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.1.1)
[2025-05-02T22:43:19.043+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (0.12.1)
[2025-05-02T22:43:19.044+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (4.57.0)
[2025-05-02T22:43:19.045+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.4.7)
[2025-05-02T22:43:19.046+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (10.4.0)
[2025-05-02T22:43:19.047+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.1.1)
[2025-05-02T22:43:19.133+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (2023.3.post1)
[2025-05-02T22:43:19.134+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (2023.4)
[2025-05-02T22:43:19.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.0.3)
[2025-05-02T22:43:19.300+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2.26.2)
[2025-05-02T22:43:19.355+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (4.0.12)
[2025-05-02T22:43:19.410+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.17.0)
[2025-05-02T22:43:19.452+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.2.14)
[2025-05-02T22:43:19.463+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (0.43b0)
[2025-05-02T22:43:19.505+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvah8ozwhx/requirements.txt (line 1)) (1.16.0)
[2025-05-02T22:43:19.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.3.2)
[2025-05-02T22:43:19.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (3.6)
[2025-05-02T22:43:19.539+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (2023.11.17)
[2025-05-02T22:43:19.641+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (1.16.0)
[2025-05-02T22:43:19.675+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (5.0.2)
[2025-05-02T22:43:19.729+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (0.3.0)
[2025-05-02T22:43:19.730+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (4.9)
[2025-05-02T22:43:19.777+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvah8ozwhx/requirements.txt (line 2)) (0.5.1)
[2025-05-02T22:43:19.825+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T22:43:19.855+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 13.8 MB/s eta 0:00:00
[2025-05-02T22:43:22.967+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T22:43:23.336+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T22:43:23.450+0000] {process_utils.py:190} INFO - 
[2025-05-02T22:43:23.451+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T22:43:23.452+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T22:43:23.697+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvah8ozwhx/bin/python /tmp/venv-callwcuyt2bm/script.py /tmp/venv-callwcuyt2bm/script.in /tmp/venv-callwcuyt2bm/script.out /tmp/venv-callwcuyt2bm/string_args.txt /tmp/venv-callwcuyt2bm/termination.log
[2025-05-02T22:43:23.706+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T22:43:24.485+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T22:43:27.456+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:27.455+0000[0m] {[34mscript.py:[0m48} INFO[0m - Starting to read processed dataset from s3://data/processed/stroke_data.csv[0m
[2025-05-02T22:43:27.467+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:27.466+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:27.556+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:27.555+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:27.623+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:27.623+0000[0m] {[34mscript.py:[0m53} INFO[0m - Processed dataset loaded successfully from s3://data/processed/stroke_data.csv[0m
[2025-05-02T22:43:27.630+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:27.629+0000[0m] {[34mscript.py:[0m61} INFO[0m - Target column for the dataset: log_cnt[0m
[2025-05-02T22:43:27.631+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:27.630+0000[0m] {[34mscript.py:[0m65} ERROR[0m - Target column 'log_cnt' not found in DataFrame. Available columns: ['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'][0m
[2025-05-02T22:43:27.636+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:27.636+0000[0m] {[34mvariable.py:[0m245} WARNING[0m - The variable target_col is defined in the LocalFilesystemBackend secrets backend, which takes precedence over reading from the database. The value in the database will be updated, but to read it you have to delete the conflicting variable from LocalFilesystemBackend[0m
[2025-05-02T22:43:28.094+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.093+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-05-02T22:43:28.098+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.097+0000[0m] {[34mscript.py:[0m69} INFO[0m - Setting target column to default value: stroke[0m
[2025-05-02T22:43:28.099+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.099+0000[0m] {[34mscript.py:[0m81} INFO[0m - Features and target separated successfully[0m
[2025-05-02T22:43:28.100+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.099+0000[0m] {[34mscript.py:[0m82} INFO[0m - Features shape: (5110, 16), Target shape: (5110,)[0m
[2025-05-02T22:43:28.102+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.102+0000[0m] {[34mscript.py:[0m86} INFO[0m - Class distribution in target column:
[2025-05-02T22:43:28.103+0000] {process_utils.py:190} INFO - stroke
[2025-05-02T22:43:28.103+0000] {process_utils.py:190} INFO - 0    95.127202
[2025-05-02T22:43:28.104+0000] {process_utils.py:190} INFO - 1     4.872798
[2025-05-02T22:43:28.104+0000] {process_utils.py:190} INFO - Name: proportion, dtype: float64[0m
[2025-05-02T22:43:28.115+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.115+0000[0m] {[34mscript.py:[0m103} INFO[0m - Test size for dataset split: 0.3[0m
[2025-05-02T22:43:28.121+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.121+0000[0m] {[34mscript.py:[0m110} INFO[0m - Dataset split into training and testing sets successfully[0m
[2025-05-02T22:43:28.122+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.121+0000[0m] {[34mscript.py:[0m111} INFO[0m - Training set size: (3577, 16), Testing set size: (1533, 16)[0m
[2025-05-02T22:43:28.123+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.123+0000[0m] {[34mscript.py:[0m116} INFO[0m - Class distribution in training set:
[2025-05-02T22:43:28.124+0000] {process_utils.py:190} INFO - stroke
[2025-05-02T22:43:28.125+0000] {process_utils.py:190} INFO - 0    95.135588
[2025-05-02T22:43:28.125+0000] {process_utils.py:190} INFO - 1     4.864412
[2025-05-02T22:43:28.126+0000] {process_utils.py:190} INFO - Name: proportion, dtype: float64[0m
[2025-05-02T22:43:28.127+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.123+0000[0m] {[34mscript.py:[0m117} INFO[0m - Class distribution in testing set:
[2025-05-02T22:43:28.127+0000] {process_utils.py:190} INFO - stroke
[2025-05-02T22:43:28.128+0000] {process_utils.py:190} INFO - 0    95.107632
[2025-05-02T22:43:28.128+0000] {process_utils.py:190} INFO - 1     4.892368
[2025-05-02T22:43:28.129+0000] {process_utils.py:190} INFO - Name: proportion, dtype: float64[0m
[2025-05-02T22:43:28.130+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.123+0000[0m] {[34mscript.py:[0m122} INFO[0m - Starting to save training and testing datasets to S3/Minio[0m
[2025-05-02T22:43:28.133+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.132+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:28.201+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.200+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:28.236+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.235+0000[0m] {[34mscript.py:[0m127} INFO[0m - Training features saved successfully to s3://data/train/stroke_data_X_train.csv[0m
[2025-05-02T22:43:28.245+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.244+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:28.421+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.421+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:28.448+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.447+0000[0m] {[34mscript.py:[0m130} INFO[0m - Testing features saved successfully to s3://data/test/stroke_data_X_test.csv[0m
[2025-05-02T22:43:28.457+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.457+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:28.526+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.526+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:28.550+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.550+0000[0m] {[34mscript.py:[0m133} INFO[0m - Training target saved successfully to s3://data/train/stroke_data_y_train.csv[0m
[2025-05-02T22:43:28.559+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.559+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T22:43:28.776+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.776+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T22:43:28.794+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.793+0000[0m] {[34mscript.py:[0m136} INFO[0m - Testing target saved successfully to s3://data/test/stroke_data_y_test.csv[0m
[2025-05-02T22:43:28.795+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:28.794+0000[0m] {[34mscript.py:[0m142} INFO[0m - Logging data split information to MLflow[0m
[2025-05-02T22:43:29.159+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:29.158+0000[0m] {[34mscript.py:[0m178} INFO[0m - Data split information logged to MLflow successfully in run: split_dataset_20250502_224328[0m
[2025-05-02T22:43:29.195+0000] {process_utils.py:190} INFO - 2025/05/02 22:43:29 INFO mlflow.tracking._tracking_service.client: 🏃 View run split_dataset_20250502_224328 at: http://mlflow:5000/#/experiments/1/runs/4e7ffd1a947843c68228381a0f44f984.
[2025-05-02T22:43:29.195+0000] {process_utils.py:190} INFO - 2025/05/02 22:43:29 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-02T22:43:29.221+0000] {process_utils.py:190} INFO - [[34m2025-05-02T22:43:29.221+0000[0m] {[34mscript.py:[0m180} INFO[0m - Dataset splitting and saving completed successfully[0m
[2025-05-02T22:43:29.802+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T22:43:29.817+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=split_dataset, execution_date=20250501T000000, start_date=20250502T224316, end_date=20250502T224329
[2025-05-02T22:43:29.838+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T22:43:29.861+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
